### ISSUE TITLE
Always getting "Android version not supported. Aborting." in MAC

### ISSUE THREAD

**Issue by fllaryora** [quarkslab/AERoot#5] opened 2021-04-30 14:04 UTC
Hello quarkslab, first thank you for create this tool.
I couldnt try it but .... your application worth the time .

I am using Android 11.0 (Google Play)
python3 aeroot.py pid 10614
AERoot (Android Emulator ROOTing system) v. 0.2
    _           _         _   _
 __|_|___      ( \       ( ) ( )
(  _____/       \ \     _| |_| |
| (|_|__    _____\ \   (_   _   _)
(_____  )  (_____)) )   _| (_) |
/\_|_|) |        / /   (_   _   _)
\_______)       / /      | | | |
   |_|         (_/       (_) (_)

**[!] Android version not supported. Aborting.**
[+] Exiting.

Well, I wasn't with my arms crossed. XD
First by touching the  phyton code I have to read the outcome of uname:
**uname -rm** return  
"5.4.47-01061-g22e35a1de440 x86_64"

Second: Install gdb (because you didnt tell me I will need it).
brew install gdb

Third Add the dictionary entry:
    "5.4.47-01061-g22e35a1de440 x86_64": {
        "name": "Android 11.0 (R) x86_64",
        "gdb_arch": "x86_64",
        "offset_to_comm": 1808,
        "offset_to_parent": 1368,
        "offset_to_tasks": 1096,
        "offset_to_creds": 1792,
        "offset_to_init_ptr": -1379768,
        "offset_to_pid": 1352,
        "kernel_ptr": 18446741874686296388,
        "selinux_offset": 1703193,
        "ptr_size": 8,
        "enforce_size": 1,
 "ps_name_cmd": "ps -A",
        "ps_pid_cmd": "ps -A -o pid="
    },
and ...
the ps command is not working in my OS !! 
I try :
        "ps_name_cmd": "ps aux | grep -v grep | grep -c [-i] ",
        "ps_pid_cmd": "ps -A -o -p "
But didnt work

Do you know how can I do to run it in MacOS ?

**Comment by Ha0ris** [comment] 2021-04-30 14:38
Hi! Thank you for the feedback.

I don't think the problem is with your host OS (even if I never tested AERoot on MAC).

> Second: Install gdb (because you didnt tell me I will need it).
> brew install gdb

I will add the requirement in the README file.

> **uname -rm** return
> "5.4.47-01061-g22e35a1de440 x86_64"

> and ...
> the ps command is not working in my OS !!

Are you running these commands on your host ? They are intented to be runned on Android through ADB.

So. Could you try: `adb shell uname -rm` (with your Android 11 running), then paste the output here ?

Regards.

**Comment by fllaryora** [comment] 2021-04-30 14:50
Wow, thank you Eric Le Guevel Ha0ris , for your very fast answer !
Here you are the output:
$ adb shell uname -rm
5.4.47-01061-g22e35a1de440 x86_64

Merci beaucoup
Thanks in advance.
Bonne journée.
Have a nice day!

**Comment by Ha0ris** [comment] 2021-04-30 15:56
Currently, AERoot only support Android 11 `R9` AVD (kernel 5.4.61-android11-0-00791-gbad091cc4bf3-ab6833933).
You can check the revision of your system image in this file: `ANDROID_SDK_PATH/system-images/android-30/google_apis_playstore/x86_64/source.properties` (Pkg.Revision).
I will implement the `R10` (the last one) support soon, so you should consider upgrading your Android 11 system image.

Regards.

**Comment by fllaryora** [comment] 2021-04-30 19:57
Hi Eric, I downloaded  a R9 version for you. 
cat source.properties
Pkg.Desc=System Image x86 with Google Play.
Pkg.Revision=9
Pkg.Dependencies=emulator#30.0.4
AndroidVersion.ApiLevel=30
SystemImage.Abi=x86
SystemImage.TagId=google_apis_playstore
SystemImage.TagDisplay=Google Play
SystemImage.GpuSupport=true
Addon.VendorId=google
Addon.VendorDisplay=Google Inc.

So It will use the entry:
  "5.4.61-android11-0-00791-gbad091cc4bf3-ab6833933 i686": {
        "name": "Android 11.0 (R) x86",
        "gdb_arch": "x86_64",
        "offset_to_comm": 1808,
        "offset_to_parent": 1368,
        "offset_to_tasks": 1096,
        "offset_to_creds": 1792,
        "offset_to_init_ptr": -1379768,
        "offset_to_pid": 1352,
        "kernel_ptr": 18446741874686296388,
        "selinux_offset": 1703193,
        "ptr_size": 8,
        "enforce_size": 1,
        "ps_name_cmd": "ps -A",
        "ps_pid_cmd": "ps -A -o pid="
    },

But 
**$ps aux | grep qemu**
_USER_          **37255**  14.6 19.6  7740052 1648020   ??  S     4:39PM  10:11.93 /Users/_USER_/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-x86_64 -netdelay none -netspeed full -avd API_30

$ python3 aeroot.py pid 37255
AERoot (Android Emulator ROOTing system) v. 0.2
    _           _         _   _
 __|_|___      ( \       ( ) ( )
(  _____/       \ \     _| |_| |
| (|_|__    _____\ \   (_   _   _)
(_____  )  (_____)) )   _| (_) |
/\_|_|) |        / /   (_   _   _)
\_______)       / /      | | | |
   |_|         (_/       (_) (_)

[+] Detected: Android 11.0 (R) x86
[!] Process [37255] is not running. Aborting.
[+] Exiting.

Have a nice weekend!

**Comment by Ha0ris** [comment] 2021-04-30 20:47
Hi!

With the `pid` mode you have to specify the **guest** process you want to root.
So if you just want something like `adb root`, use the daemon mode: `python3 aeroot.py daemon`
Then, any shell you'll spawn with `adb shell` after that will be root privileged.

**Comment by fllaryora** [comment] 2021-05-03 13:12
Hello Eric,
Thank you for teaching me and your patience.
I got the PID of __ia32_co+
and after run it
[+] Detected: Android 11.0 (R) x86
[+] Search for [7926] process in memory (this may take a while) ...
**[!] Gdb timed out. Make sure gdbserver is running on guest (-qemu -s).**
[+] Exiting.

Do you know how to check it on guest (inside the emulator) ?

**Comment by Ha0ris** [comment] 2021-05-03 14:07
> Hello Eric,
> Thank you for teaching me and your patience.
> I got the PID of __ia32_co+
> and after run it
> [+] Detected: Android 11.0 (R) x86
> [+] Search for [7926] process in memory (this may take a while) ...
> **[!] Gdb timed out. Make sure gdbserver is running on guest (-qemu -s).**
> [+] Exiting.
> 
> Do you know how to check it on guest (inside the emulator) ?

Hi. When you start your emulator, you must specify `-qemu -s` in the command line like that:
~~~
emulator -avd API_30 -qemu -s
~~~

Without this option, this is no gdbserver running on qemu, so AERoot can't work properly.

**Comment by fllaryora** [comment] 2021-05-03 16:05
Hello Eric,
After run 
**$ ./emulator -netdelay none -netspeed full -avd API_30_1 -qemu -s**
emulator: WARNING: Ignoring invalid http proxy: Bad format: invalid proxy name
emulator: INFO: boot completed
emulator: INFO: boot time 32284 ms
emulator: Increasing screen off timeout, logcat buffer size to 2M.
emulator: Revoking microphone permissions for Google App.

[+] Detected: Android 11.0 (R) x86
[+] Search for [4977] process in memory (this may take a while) ...
[!] [4977] process not found in memory. Aborting.
[+] Exiting.

Do you know what that means?
Thanks in advance.

**Comment by Ha0ris** [comment] 2021-05-03 16:24
Hi.

Could you try to run: `python3 aeroot -v daemon`, then paste the output here ?

Thank you in advance.

**Comment by fllaryora** [comment] 2021-05-03 18:16
Thank you for all your support. 
$ python3 aeroot.py -v daemon
AERoot (Android Emulator ROOTing system) v. 0.2
 [-] Loading xxxx/AERoot/config.json ...
[+] Detected: Android 11.0 (R) x86
 [-] [adbd] process is running
[+] Search for [adbd] process in memory (this may take a while) ...
 [-] Init task_struct found at: -0x448
 [-] Looking at 0xf000ff53f000de7b - []
[!] [adbd] process not found in memory. Aborting.
[+] Exiting.

Thank you in advance.

**Comment by Ha0ris** [comment] 2021-05-03 22:39
I am not 100% sure, but it may be due to the KASLR bypass.

You should try the [experimental branch](https://github.com/quarkslab/AERoot/tree/experimental).
And also, since Android 11, this may take some time for the kernel to be correctly mapped into virtual memory, so you should also wait few seconds after your Android starts running to run aeroot.

**Comment by Ha0ris** [comment] 2021-06-13 21:57
The issue should be fixed as the experimental has been merged in master.
There still a problem (sometimes) with the emulator cold boot on *macOS*. A workaround has been added at the end of the README.

**Closed by Ha0ris** 2021-06-13 21:57 UTC
Labels: bug, documentation
